branch-defaults:
  master:
    environment: null
global:
  application_name: ExpressProject
  default_ec2_keyname: aws-eb
  default_platform: Node.js
  default_region: us-west-2
  profile: null
  sc: git
